apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-pety
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-pety@sha256:3c188c38da5377fac5049e08f94b8e112403f1f23309d425281675fe768a8fd5
        name: my-nodejs
        resources: {}
status: {}
